metal:
  children:
    masters:
      hosts:
        #metal0: {ansible_host: 192.168.50.61, mac: '8c:16:45:ba:be:24', disk: sda, network_interface: eno1} # m920q
        metal0:  {ansible_host: 192.168.50.62, mac: 'f8:b4:6a:b8:56:f18', disk: sda, network_interface: eno1} # prodesk2
    workers:
      hosts:
        #metal1: {ansible_host: 192.168.50.64, mac: 'bc:e9:2f:83:0c:46', disk: sda, network_interface: eno1} # hpmp9
        #metal2: {ansible_host: 192.168.50.65, mac: '80:e8:2c:1a:74:71', disk: sda, network_interface: eno1} # prodesk1     
        #metal3: {ansible_host: 192.168.50.62, mac: 'f8:b4:6a:b8:56:f18', disk: sda, network_interface: eno1} # prodesk2
